// DESTRUCTURING 
// let obj={ id :1 , name:"Rajan" , color:"white", subject:"DSA"};
// let {id,name} =obj;            
// console.log(obj);
// console.log(name);
// console.log(subject); // agar let ke sath 


// let obj={ id :1 , name:"Rajan" , color:"white", subject:"DSA"};
// let {id,name, ...obj2} =obj;            
// console.log(obj2);


let arr1=["apple",2];
let arr2=[...arr1,3,4];
console.log(arr2);